export const LIHAT_TRANSAKSI: string = 'Lihat Transaksi'
export const PENGECEKAN: string = 'Pengecekan'
export const BERHASIL: string = 'Berhasil'
export const PENDING: string = 'PENDING'
export const SUCCESS: string = 'SUCCESS'
export const SEARCH_PLACEHOLDER: string = 'Cari nama, bank, atau nominal'
export const URUTKAN: string = 'URUTKAN'
export const DATA_TIDAK_DITEMUKAN: string = 'Data tidak ditemukan. Coba cari nama, bank, atau nominal yang lain.'